APP_ID: "550486885068789"
APP_SECRET: "76d074979efd4d2807b2e6e7c9c820d0"

ACCESS_TOKEN: "CAAH0qjc87ZCUBAMLOqDrWwOfLWnlNuvHCWejLNsXGS2raaytaaf7iMvl9e6bKJbUWKlBiHSp3p1RbiJoigxZBCudUtfwgQmoxMAooD62T4ZAWAtpdYMSRJrDmjNKuNwtZBA2CFSr7Hwvwh4ZCH7LQHW7VbcXRGJP8wiN9giMlPurCHwPlAIx844GPdvNDzs8ZD"

LONG_TERM_TOKEN: "CAAH0qjc87ZCUBAPxckQyHh8z33j3EOstauKhp8U35YZCyNgC5xOhRNQU83MJGOVw4ofZBZACKI9rhZArR6M4KQFXYqLgA701mevLwdQn4SwlH54ZApupIRFlIPjH0tvjtn3fpJnOSSOzQ0AmoX4j6SZBRKKgRCn1x4PZC8ZCUeMnst0AqaU5pVmrGZCsQbC1Kgyn4ZD"

