APP_ID: "613051635469572"
APP_SECRET: "256895c8d42d1fb08194b2b7804e6357"

ACCESS_TOKEN: "CAAItkTT2DQQBAE0TZB0L6ZCM4czWZAlG6t3QDkJzeweFxW6BK6fk4ZBtS5NFJ15xOxsEZCgopd4WjiIv2VCRZC1yXTFRSLSZAjmgmlTbTcQgZCMMQaxh8pX6tCFSrodIS4wQee5MBqyvme0NJcGp6VmKT3AjlMc4qV1VaZB9NRC0el4jgeuO0nP0ZChvbK4ojIZAcIZD"

LONG_TERM_TOKEN: "CAAItkTT2DQQBANXiEuKMm3gfYE73J6CUTNYTZA0YwOEIiNA2vkGNPXMXaEZCP6BcJzW4W9pTEyKnujsRBPUd0sbZAQtcpZCUQZC1u6K0ppig5wMiZBgDZCsktXvxDb9VTzFd8eZAudM4rxMNly7OP7G2xFlzZCRErNVfwARSSUH4GKISfvm2JdzEpPb0QW0koYQ8ZD"